#' <% param_vals = if (exists("param_vals", inherits = FALSE)) paste0(", ", param_vals)%>
#'
#' @examplesIf torch::torch_is_installed()
#' # Construct the PipeOp
#' pipeop = po("<%=id %>"<%=param_vals%>)
#' pipeop
#' # The available parameters
#' pipeop$param_set



# Maybe finish this at some point
# @examplesIf torch::torch_is_installed()
# md = ModelDescriptor(
#   graph =
# )
#
# # The graph of the model descriptor is modified in-place
# graph = md$graph
#
#
# # These are the output shapes generated by the pipeop for the given task
# pipeop$shapes_out(md$pointer_shape)
#
# # Apply the pipeop to the model descriptor
# mdout = pipeop$train(list(md))[[1L]]
# mdout
#
# # A PipeOpModule was generated by the PipeOpTorch and added to the graph
# graph$edges
# graph$pipeops$<%=id%>$module
#
# # The pointer is updated to the output channel of the applied pipeop
# c(pipeop$id, pipeop$output$name)
# mdout$pointer
#
# # The shapes are equal to those calculated by `$shapes_out()` above
# mdout$pointer_shape
