test_that("Architecture is working", {
  task = tsk("iris")
  a = Architecture$new()
  a$add_torchop(top("tokenizer", d_token = 3L))
  a$add_torchop(top("flatten"))
  a$add_torchop(top("linear", out_features = 1L))
  a$add_torchop(top("relu"))
  a$add_edge("tokenizer", "flatten")
  a$add_edge("flatten", "linear")
  a$add_edge("linear", "relu")
  net = a$build(task)
  expect_r6(net, "nn_Graph")
})
