---
title: "Pipeline example"
author: "Sebastian Fischer"
date: "2/14/2022"
output: html_document
---

## Building torch networks with PipeOp's


```{r cars}
library(torch)
library(mlr3torch)
library(mlr3pipelines)
library(mlr3)

graph = Graph$new()
to_input = TorchOpInput$new()
to_linear1 = TorchOpLinear$new("linear_1")
to_linear1$param_set$values$out_features = 10
to_relu = TorchOpReLU$new()
to_linear2 = TorchOpLinear$new("linear_2")
to_linear2$param_set$values$out_features = 1
to_model = TorchOpModel$new()
to_model$param_set$values$optimizer = "optim_adam"
to_model$param_set$values$criterion = "nn_mse_loss"
to_model$param_set$values$device = "cpu"
to_model$param_set$values$n_epochs = 0
to_model$param_set$values$batch_size = 1

graph$add_pipeop(to_input)
graph$add_pipeop(to_linear1)
graph$add_pipeop(to_relu)
graph$add_pipeop(to_linear2)
graph$add_pipeop(to_model)

graph$add_edge(src_id = "input", dst_id = "linear1", src_channel = "task",
  dst_channel = "task")
graph$add_edge(src_id = "input", dst_id = "linear1",
  src_channel = "architecture", dst_channel = "architecture")
graph$add_edge(src_id = "linear1", dst_id = "relu", src_channel = "task",
  dst_channel = "task")
graph$add_edge(src_id = "linear1", dst_id = "relu",
  src_channel = "architecture", dst_channel = "architecture")
graph$add_edge(src_id = "relu", dst_id = "linear2", src_channel = "task",
  dst_channel = "task")
graph$add_edge(src_id = "relu", dst_id = "linear2",
  src_channel = "architecture", dst_channel = "architecture")
graph$add_edge(src_id = "linear2", dst_id = "model", src_channel = "task",
  dst_channel = "task")
graph$add_edge(src_id = "linear2", dst_id = "model",
  src_channel = "architecture", dst_channel = "architecture")

task = tsk("mtcars")
graph$train(task)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
