# r cmd check workflow of the mlr3 ecosystem v0.2.0
# https://github.com/mlr-org/actions
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 4 * * 1'


name: r-cmd-check

jobs:
  r-cmd-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TORCH_INSTALL: 1
      INCLUDE_IGNORED: "true"

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'devel'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Install additional packages
        run: |
          Rscript -e 'install.packages("rappdirs")'

      - name: Get torchvision package version
        id: get_package_version
        run: echo "##[set-output name=torchvision_package_version;]$(Rscript -e 'packageVersion("torchvision")')"

      - name: Get torch cache path
        id: get_cache_path
        run: echo "##[set-output name=torch_cache_path;]$(Rscript -e 'cat(rappdirs::user_cache_dir("torch"))')"

      - name: Cache Torchvision Downloads
        uses: actions/cache@v3
        with:
          path: ${{ steps.get_cache_path.outputs.torch_cache_path }}
          key: ${{ runner.os }}-r-${{ steps.get_version.outputs.torchvision_package_version}}
      - uses: r-lib/actions/check-r-package@v2

      - uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
